name: $(Build.DefinitionName)_$(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

pool:
  vmImage: 'windows-latest'

stages:
  - stage: Deploy_ARM_Template
    displayName: Deploy_ARM_Template
    jobs:
    - job: 'Deploy_Azure_Resource'
      steps: 
      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'Dev'
          subscriptionId: '3f4b1df0-5d35-4ac1-a042-6a2eccf5bf1a'
          action: 'Create Or Update Resource Group'
          resourceGroupName: 'explore_azure_rest_api'
          location: 'East US'
          templateLocation: 'Linked artifact'
          csmFile: '$(System.DefaultWorkingDirectory)\$(TemplateName)\main.json'
          csmParametersFile: '$(System.DefaultWorkingDirectory)\$(TemplateName)\parameters.json'
          deploymentMode: 'Incremental'